"""add_fields_for_deterministic_recon

Revision ID: 10410ac93dba
Revises: 4d0d113cc0fb
Create Date: 2026-08-09 11:28:59.223908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '10410ac93dba'
down_revision: Union[str, Sequence[str], None] = '4d0d113cc0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erp_invoices', sa.Column('supplier_gstin', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_erp_invoices_supplier_gstin'), 'erp_invoices', ['supplier_gstin'], unique=False)
    op.add_column('gstr2b_invoices', sa.Column('doc_no', sa.String(length=100), nullable=True))
    op.add_column('gstr2b_invoices', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('gstr2b_invoices', sa.Column('gst_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('ims_reconciliations', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ims_reconciliations', 'reasoning')
    op.drop_column('gstr2b_invoices', 'gst_amount')
    op.drop_column('gstr2b_invoices', 'amount')
    op.drop_column('gstr2b_invoices', 'doc_no')
    op.drop_index(op.f('ix_erp_invoices_supplier_gstin'), table_name='erp_invoices')
    op.drop_column('erp_invoices', 'supplier_gstin')
    # ### end Alembic commands ###
