"""add_roles_to_ca_users

Revision ID: 4d0d113cc0fb
Revises: 71b2369f9cff
Create Date: 2026-08-08 14:20:17.124319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4d0d113cc0fb'
down_revision: Union[str, Sequence[str], None] = '71b2369f9cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
