"""add_ca_firm_and_user_models

Revision ID: 58726f5cdcdf
Revises: b5eb59cd0001
Create Date: 2026-08-07 12:34:54.201316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '58726f5cdcdf'
down_revision: Union[str, Sequence[str], None] = 'b5eb59cd0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_firms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ca_firms_id'), 'ca_firms', ['id'], unique=False)
    op.create_table('ca_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['ca_firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ca_users_email'), 'ca_users', ['email'], unique=True)
    op.create_index(op.f('ix_ca_users_firm_id'), 'ca_users', ['firm_id'], unique=False)
    op.create_index(op.f('ix_ca_users_id'), 'ca_users', ['id'], unique=False)
    op.add_column('tenants', sa.Column('firm_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tenants_firm_id'), 'tenants', ['firm_id'], unique=False)
    op.create_foreign_key(None, 'tenants', 'ca_firms', ['firm_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_firm_id'), table_name='tenants')
    op.drop_column('tenants', 'firm_id')
    op.drop_index(op.f('ix_ca_users_id'), table_name='ca_users')
    op.drop_index(op.f('ix_ca_users_firm_id'), table_name='ca_users')
    op.drop_index(op.f('ix_ca_users_email'), table_name='ca_users')
    op.drop_table('ca_users')
    op.drop_index(op.f('ix_ca_firms_id'), table_name='ca_firms')
    op.drop_table('ca_firms')
    # ### end Alembic commands ###
