"""add_roles_to_ca_users

Revision ID: 71b2369f9cff
Revises: 4f0bae16c2be
Create Date: 2026-08-08 14:15:40.467930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# pyrefly: ignore [missing-import]
import pgvector


# revision identifiers, used by Alembic.

revision: str = '71b2369f9cff'
down_revision: Union[str, Sequence[str], None] = '4f0bae16c2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'CLERK', name='user_role_enum')
    user_role_enum.create(op.get_bind())
    op.add_column('ca_users', sa.Column('role', user_role_enum, server_default='CLERK', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_users', 'role')
    user_role_enum = sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'CLERK', name='user_role_enum')
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
