"""initial_taxon_schema

Revision ID: b5eb59cd0001
Revises: 
Create Date: 2026-08-03 12:34:28.780223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# pyrefly: ignore [missing-import]
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'b5eb59cd0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_gstin'), 'tenants', ['gstin'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('erp_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('doc_no', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vector_embed', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_erp_invoices_hnsw', 'erp_invoices', ['vector_embed'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector_embed': 'vector_cosine_ops'})
    op.create_index(op.f('ix_erp_invoices_tenant_id'), 'erp_invoices', ['tenant_id'], unique=False)
    op.create_table('gstr2b_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('irn', sa.String(length=64), nullable=True),
    sa.Column('vector_embed', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('irn')
    )
    op.create_index('idx_gstr2b_invoices_hnsw', 'gstr2b_invoices', ['vector_embed'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector_embed': 'vector_cosine_ops'})
    op.create_index(op.f('ix_gstr2b_invoices_supplier_gstin'), 'gstr2b_invoices', ['supplier_gstin'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoices_tenant_id'), 'gstr2b_invoices', ['tenant_id'], unique=False)
    op.create_table('tally_sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tdl_query_xml', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='tally_job_status_enum'), nullable=False),
    sa.Column('circuit_breaker_state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='circuit_breaker_state_enum'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tally_sync_jobs_status'), 'tally_sync_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_tally_sync_jobs_tenant_id'), 'tally_sync_jobs', ['tenant_id'], unique=False)
    op.create_table('tds_ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tds_deducted', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tds_tenant_pan_sec', 'tds_ledgers', ['tenant_id', 'pan', 'section'], unique=False)
    op.create_index(op.f('ix_tds_ledgers_pan'), 'tds_ledgers', ['pan'], unique=False)
    op.create_index(op.f('ix_tds_ledgers_tenant_id'), 'tds_ledgers', ['tenant_id'], unique=False)
    op.create_table('ims_reconciliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('erp_id', sa.UUID(), nullable=False),
    sa.Column('gstr2b_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPT', 'REJECT', name='recon_status_enum'), nullable=False),
    sa.Column('cgst_17_5_flag', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['erp_id'], ['erp_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gstr2b_id'], ['gstr2b_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('erp_id')
    )
    op.create_index(op.f('ix_ims_reconciliations_status'), 'ims_reconciliations', ['status'], unique=False)
    op.create_table('tds_anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('reconstruction_loss', sa.Float(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('rag_rectification_draft', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['tds_ledgers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ledger_id')
    )
    op.create_index('idx_active_tds_anomalies', 'tds_anomalies', ['is_anomalous'], unique=False, postgresql_where=sa.text('is_anomalous IS true'))
    op.create_index(op.f('ix_tds_anomalies_is_anomalous'), 'tds_anomalies', ['is_anomalous'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tds_anomalies_is_anomalous'), table_name='tds_anomalies')
    op.drop_index('idx_active_tds_anomalies', table_name='tds_anomalies', postgresql_where=sa.text('is_anomalous IS true'))
    op.drop_table('tds_anomalies')
    op.drop_index(op.f('ix_ims_reconciliations_status'), table_name='ims_reconciliations')
    op.drop_table('ims_reconciliations')
    op.drop_index(op.f('ix_tds_ledgers_tenant_id'), table_name='tds_ledgers')
    op.drop_index(op.f('ix_tds_ledgers_pan'), table_name='tds_ledgers')
    op.drop_index('idx_tds_tenant_pan_sec', table_name='tds_ledgers')
    op.drop_table('tds_ledgers')
    op.drop_index(op.f('ix_tally_sync_jobs_tenant_id'), table_name='tally_sync_jobs')
    op.drop_index(op.f('ix_tally_sync_jobs_status'), table_name='tally_sync_jobs')
    op.drop_table('tally_sync_jobs')
    op.drop_index(op.f('ix_gstr2b_invoices_tenant_id'), table_name='gstr2b_invoices')
    op.drop_index(op.f('ix_gstr2b_invoices_supplier_gstin'), table_name='gstr2b_invoices')
    op.drop_index('idx_gstr2b_invoices_hnsw', table_name='gstr2b_invoices', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector_embed': 'vector_cosine_ops'})
    op.drop_table('gstr2b_invoices')
    op.drop_index(op.f('ix_erp_invoices_tenant_id'), table_name='erp_invoices')
    op.drop_index('idx_erp_invoices_hnsw', table_name='erp_invoices', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector_embed': 'vector_cosine_ops'})
    op.drop_table('erp_invoices')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_gstin'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
